"use client";

import { useEffect, useState } from "react";
import type { Blueprint } from "../types/blueprint";
import { motion } from "framer-motion";
import mermaid from "mermaid";
import {
  Copy,
  Check,
  FileCode,
  Network,
  FolderTree,
  AlertTriangle,
} from "lucide-react";

type Props = {
  blueprint: Blueprint | null;
};

export function BlueprintView({ blueprint }: Props) {
  const [copied, setCopied] = useState(false);
  const [diagramSvg, setDiagramSvg] = useState<string | null>(null);
  const [diagramError, setDiagramError] = useState(false);

  // --- SMART CLEANER (Η Λύση στο πρόβλημα) ---
  const getCleanMermaidCode = (raw: string) => {
    if (!raw) return "";
    let cleaned = raw
      .replace(/```mermaid/g, "") // Αφαιρεί ```mermaid
      .replace(/```/g, "") // Αφαιρεί ```
      .replace(/^[\s\n]+/, "") // Αφαιρεί κενά στην αρχή
      .replace(/[\s\n]+$/, ""); // Αφαιρεί κενά στο τέλος

    // ΔΙΟΡΘΩΣΗ: Αν το AI βάλει λάθος βέλος τύπου "-->|text|>" το κάνουμε "-->|text|"
    cleaned = cleaned.replace(/-->\|(.*?)\|>/g, "-->|$1|");

    // ΔΙΟΡΘΩΣΗ: Αν βάλει διπλά βέλη κατά λάθος
    cleaned = cleaned.replace(/--> >/g, "-->");

    return cleaned;
  };

  useEffect(() => {
    if (blueprint?.mermaidDiagram) {
      const code = getCleanMermaidCode(blueprint.mermaidDiagram);

      // Αρχικοποίηση
      mermaid.initialize({
        startOnLoad: false,
        theme: "dark",
        securityLevel: "loose",
        fontFamily: "monospace",
      });

      const renderDiagram = async () => {
        try {
          // Δημιουργούμε ένα μοναδικό ID για κάθε render
          const uniqueId = `mermaid-${Date.now()}`;

          // Η render επιστρέφει το SVG string (χωρίς να πειράξει το DOM απευθείας)
          const { svg } = await mermaid.render(uniqueId, code);
          setDiagramSvg(svg);
          setDiagramError(false);
        } catch (err) {
          console.error("Mermaid Render Failed:", err);
          setDiagramError(true);
        }
      };

      renderDiagram();
    }
  }, [blueprint]);

  if (!blueprint) {
    return (
      <div className="mt-10 rounded-2xl border border-dashed border-blue-300/20 bg-blue-900/10 p-10 text-center text-sm text-blue-300/50">
        <p>System awaiting input...</p>
        <p className="text-xs mt-2">
          Describe your app idea to generate architecture.
        </p>
      </div>
    );
  }

  const handleCopy = () => {
    const md = `
# Project Blueprint
Generated by AI Architect

## Feature List
${blueprint.featureList.map((f) => `- ${f}`).join("\n")}

## Tech Stack
- Frontend: ${blueprint.techStack.frontend}
- Backend: ${blueprint.techStack.backend}
- Database: ${blueprint.techStack.database}

## Architecture
${blueprint.architecture}

## Database Schema
${blueprint.databaseSchema}
    `;
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const container = {
    hidden: {},
    visible: { transition: { staggerChildren: 0.1 } },
  };

  const item = {
    hidden: { opacity: 0, y: 10 },
    visible: { opacity: 1, y: 0 },
  };

  return (
    <div className="relative">
      {/* EXPORT BUTTON */}
      <div className="absolute top-0 right-0 z-10">
        <button
          onClick={handleCopy}
          className="flex items-center gap-2 bg-blue-600 hover:bg-blue-500 text-white px-4 py-2 rounded-md text-xs font-bold uppercase tracking-wider transition-all shadow-lg border border-blue-400/20"
        >
          {copied ? (
            <Check className="w-4 h-4" />
          ) : (
            <Copy className="w-4 h-4" />
          )}
          {copied ? "Copied!" : "Export to Markdown"}
        </button>
      </div>

      <motion.div
        className="mt-12 grid gap-6 md:grid-cols-2"
        initial="hidden"
        animate="visible"
        variants={container}
      >
        {/* 1. VISUAL ARCHITECTURE (Mermaid) */}
        <motion.section
          variants={item}
          className="md:col-span-2 rounded-xl border border-blue-500/20 bg-black/40 p-6 shadow-sm overflow-hidden min-h-[300px]"
        >
          <div className="flex items-center gap-2 mb-4 border-b border-blue-500/10 pb-2">
            <Network className="w-4 h-4 text-blue-400" />
            <h2 className="text-sm font-bold uppercase tracking-widest text-blue-100">
              System Diagram
            </h2>
          </div>

          <div className="flex justify-center py-4 bg-slate-900/30 rounded-lg overflow-x-auto">
            {diagramError ? (
              <div className="text-red-400 text-xs flex flex-col items-center gap-2 p-4 w-full">
                <AlertTriangle className="w-6 h-6" />
                <p>Visualization Syntax Error</p>
                <div className="w-full bg-black/50 p-3 rounded mt-2 border border-red-500/20">
                  <p className="mb-2 text-slate-500">
                    Raw code returned by AI:
                  </p>
                  <pre className="text-[10px] text-green-300 font-mono whitespace-pre-wrap break-all">
                    {getCleanMermaidCode(blueprint.mermaidDiagram)}
                  </pre>
                </div>
              </div>
            ) : diagramSvg ? (
              <div
                className="mermaid-svg-container opacity-90"
                dangerouslySetInnerHTML={{ __html: diagramSvg }}
              />
            ) : (
              <div className="text-blue-300/30 text-xs animate-pulse">
                Rendering Diagram...
              </div>
            )}
          </div>
        </motion.section>

        {/* 2. FILE STRUCTURE TREE */}
        <motion.section
          variants={item}
          className="row-span-2 rounded-xl border border-blue-500/20 bg-slate-900/60 p-6 shadow-sm"
        >
          <div className="flex items-center gap-2 mb-4 border-b border-blue-500/10 pb-2">
            <FolderTree className="w-4 h-4 text-yellow-400" />
            <h2 className="text-sm font-bold uppercase tracking-widest text-blue-100">
              Project Structure
            </h2>
          </div>
          <pre className="text-[10px] md:text-xs text-green-300 font-mono leading-relaxed whitespace-pre-wrap">
            {blueprint.folderStructure}
          </pre>
        </motion.section>

        {/* 3. TECH STACK */}
        <motion.section
          variants={item}
          className="rounded-xl border border-blue-500/20 bg-slate-900/60 p-6 shadow-sm"
        >
          <div className="flex items-center gap-2 mb-4 border-b border-blue-500/10 pb-2">
            <FileCode className="w-4 h-4 text-purple-400" />
            <h2 className="text-sm font-bold uppercase tracking-widest text-blue-100">
              Tech Stack
            </h2>
          </div>
          <ul className="space-y-2 text-xs text-slate-300">
            {Object.entries(blueprint.techStack).map(([key, value]) => (
              <li
                key={key}
                className="flex justify-between border-b border-white/5 pb-1 last:border-0"
              >
                <span className="capitalize text-slate-400">{key}:</span>
                <span className="font-mono text-blue-200">{value}</span>
              </li>
            ))}
          </ul>
        </motion.section>

        {/* 4. FEATURES */}
        <motion.section
          variants={item}
          className="rounded-xl border border-blue-500/20 bg-slate-900/60 p-6 shadow-sm"
        >
          <h2 className="text-sm font-bold uppercase tracking-widest text-blue-100 mb-4 border-b border-blue-500/10 pb-2">
            Core Features
          </h2>
          <ul className="space-y-2 text-xs text-slate-300">
            {blueprint.featureList.map((f, i) => (
              <li key={i} className="flex gap-2">
                <span className="text-blue-500">▹</span> {f}
              </li>
            ))}
          </ul>
        </motion.section>

        {/* 5. DATABASE & API */}
        <motion.section
          variants={item}
          className="md:col-span-2 rounded-xl border border-blue-500/20 bg-slate-900/60 p-6 shadow-sm"
        >
          <div className="grid md:grid-cols-2 gap-8">
            <div>
              <h2 className="text-sm font-bold uppercase tracking-widest text-blue-100 mb-2">
                Database Schema
              </h2>
              <pre className="text-[10px] text-slate-300 whitespace-pre-wrap font-mono bg-black/20 p-3 rounded-lg border border-white/5">
                {blueprint.databaseSchema}
              </pre>
            </div>
            <div>
              <h2 className="text-sm font-bold uppercase tracking-widest text-blue-100 mb-2">
                API Endpoints
              </h2>
              <ul className="space-y-1 text-[10px] font-mono text-orange-200/80">
                {blueprint.apiEndpoints.map((ep, i) => (
                  <li
                    key={i}
                    className="bg-orange-900/10 px-2 py-1 rounded border border-orange-500/10"
                  >
                    {ep}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </motion.section>

        {/* 6. TIMELINE & RISKS */}
        <motion.section
          variants={item}
          className="md:col-span-2 grid md:grid-cols-2 gap-6"
        >
          <div className="rounded-xl border border-blue-500/20 bg-slate-900/60 p-6">
            <h2 className="text-sm font-bold uppercase tracking-widest text-green-400 mb-3">
              Timeline
            </h2>
            <ul className="space-y-2 text-xs text-slate-300">
              {blueprint.timeline.map((t, i) => (
                <li key={i}>⏱ {t}</li>
              ))}
            </ul>
          </div>
          <div className="rounded-xl border border-red-500/20 bg-red-900/10 p-6">
            <h2 className="text-sm font-bold uppercase tracking-widest text-red-400 mb-3">
              Risk Assessment
            </h2>
            <ul className="space-y-2 text-xs text-red-200/70">
              {blueprint.risks.map((r, i) => (
                <li key={i}>⚠ {r}</li>
              ))}
            </ul>
          </div>
        </motion.section>
      </motion.div>
    </div>
  );
}
